### ISSUE TITLE
Advisory: Python Django CVE-2020-13254

### ISSUE THREAD

**Issue by rback123** [OSSIndex/vulns#103]
**Advisory details**
```
  URL: https://www.djangoproject.com/weblog/2020/jun/03/security-releases/
  format: pypi
  namespace:
  name: django
  versions: 2.2 before 2.2.13 and 3.0 before 3.0.7
```

**More information**

https://nvd.nist.gov/vuln/detail/CVE-2020-13254 -- CVE-2020-13254  
> In cases where a memcached backend does not perform key validation, passing malformed cache keys could result in a key collision, and potential data leakage. In order to avoid this vulnerability, key validation is added to the memcached cache backends. 

There appears to be one other missing advisory for Django on the same security release. Should I submit it separately? See  CVE-2020-13596 on https://www.djangoproject.com/weblog/2020/jun/03/security-releases/
