### ISSUE TITLE
Python elastic-apm CVE-2019-7617

### ISSUE THREAD

**Issue by rback123** [OSSIndex/vulns#110]
**Advisory details**
```
  URL: https://nvd.nist.gov/vuln/detail/CVE-2019-7617
  format: pypi
  namespace: 
  name: elastic-apm
  versions: < 5.1.0
```

**More information**

https://nvd.nist.gov/vuln/detail/CVE-2019-7617
>>>
When the Elastic APM agent for Python versions before 5.1.0 is run as a CGI script, there is a variable name clash flaw if a remote attacker can control the proxy header. This could result in an attacker redirecting collected APM data to a proxy of their choosing.
>>>

1. https://discuss.elastic.co/t/elastic-apm-agent-for-python-5-1-0-security-update/196145
1. https://pypi.org/project/elastic-apm/
