### ISSUE TITLE
TensorFlow - CVE-2021-37690

### ISSUE THREAD

**Issue by kekkegenkai** [OSSIndex/vulns#201]
It seems that CVE-2021-37690 is not present for the packages tensorflow, tensorflow-cpu, tensorflow-gpu < 2.6.0 

**Advisory details**
```
  URL: https://nvd.nist.gov/vuln/detail/CVE-2021-37690
  format: pypi
  namespace: 
  name: tensorflow, tensorflow-cpu, tensorflow-gpu
  versions: < 2.6.0 
```

**More information**
https://github.com/tensorflow/tensorflow/security/advisories/GHSA-3hxh-8cp2-g4hg
