### ISSUE TITLE
Advisory: Missing CVE-2021-23424

### ISSUE THREAD

**Issue by nille** [OSSIndex/vulns#207]
To facilitate future automation, please use the following format

**Advisory details**
```
  URL: https://github.com/advisories/GHSA-whgm-jr23-g3j9
  format: npm
  namespace: 
  name: ansi-html
  versions: <= 0.0.7
```

**More information**
This affects all versions of package ansi-html. If an attacker provides a malicious string, it will get stuck processing the input for an extremely long time.
