### ISSUE TITLE
Missing CVE-2020-15366

### ISSUE THREAD

**Issue by Shortfinga** [OSSIndex/vulns#229]
To facilitate future automation, please use the following format

**Advisory details**
```
  URL: https://github.com/ajv-validator/ajv/issues/1267#issuecomment-680000486
  format: npm
  namespace:
  name: ajv
  versions: < v6.12.3
```

**More information**
See also: CVE-2020-15366
