### ISSUE TITLE
Missing Advisory: CVE-2021-41238

### ISSUE THREAD

**Issue by MarkusGeigerDev** [OSSIndex/vulns#258]
To facilitate future automation, please use the following format

**Advisory details**
```
  URL: https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-41238
  format: nuget
  namespace: 
  name: Hangfire
  versions: 1.7.25
```

**More information**
Any additional information that might be useful/interesting
