### ISSUE TITLE
Missing Advisory: github.com/gorilla/websocket <= 1.4.0: GHSA-jf24-p9p9-4rjh

### ISSUE THREAD

**Issue by DarthHater** [OSSIndex/vulns#80]
For: https://ossindex.sonatype.org/component/pkg:golang/github.com/gorilla/websocket@1.4.0 I would expect to see this advisory:

**Advisory details**
```
  URL: https://github.com/gorilla/websocket/security/advisories/GHSA-jf24-p9p9-4rjh
  format: golang
  namespace: 
  name: github.com/gorilla/websocket
  versions: <= 1.4.0
```

**More information**
Any additional information that might be useful/interesting

Version 1.4.1 and up have been patched to avoid this vulnerability. Being this was filed on GitHub I imagine that is why it is missing (not a CVE), so we should likely be looking at the GH security advisories as a new source for golang.
